"""add language to posts

Revision ID: 21bf91096a8f
Revises: a45d7bca9833
Create Date: 2026-02-22 06:33:38.144815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21bf91096a8f'
down_revision = 'a45d7bca9833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removed alter_column for followers table - SQLite doesn't support ALTER COLUMN
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
